apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "schedulebox.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "schedulebox.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.web.env | first | index "value" | quote }}
  LOG_LEVEL: {{ (index .Values.web.env 1).value | quote }}
  LOG_FORMAT: {{ (index .Values.web.env 2).value | quote }}
  APP_URL: "https://{{ (index .Values.ingress.hosts 0).host }}"
  API_URL: "https://{{ (index .Values.ingress.hosts 0).host }}/api/v1"
  AI_SERVICE_URL: "http://{{ include "schedulebox.fullname" . }}-ai:{{ .Values.aiService.service.port }}"
